### ISSUE TITLE
support GARMIN watch

### ISSUE THREAD

**Issue by algila** [fg1/BLEHeartRateLogger#11]
Hi,
I have raspberry zero with bluez 5.43
heart rate sensor Bontrager recognized as F6:86:FE:E8:DD:70 vívoactive HR  
I get the following error, may you kindly assis keeping it working ?

pi@raspberrypi:~/Downloads/BLEHeartRateLogger-master $ ./BLEHeartRateLogger.py -m F6:86:FE:E8:DD:70 -o hrm_data.db
2019-06-30 18:59:09,746  Establishing connection to F6:86:FE:E8:DD:70
2019-06-30 18:59:10,190  Connected to F6:86:FE:E8:DD:70
2019-06-30 18:59:21,431  Couldn't find the heart rate measurement handle?!

**Comment by fg1** [comment]
@algila Thank you for your request. Could you provide me with the model name of your Garmin watch? Depending on your model, broadcasting of the heart-rate value over Bluetooth might not be included.

**Comment by algila** [comment]
Hi,
It is GARMIN vivoactive HR

https://buy.garmin.com/it-IT/IT/p/538374

**Comment by jones139** [comment]
I don't think that the Garmin supports that sort if BLE profile (but please
say if I am wrong).  My app accesses the Garmin hr data using Garmin's own
api and sends the data to the phone as an http request.  (
Http://github.com/openseizuredetector if it is any use to you - the android
code is in the Androud_Pebble_sd repository and the garmin code in
Garmin_sd)

**Comment by drkingpo** [comment]
I had the same issue with a noname hr stap.
I increased the Timeout from 10sec to 30sec at the handle Check section.
This helped

**Comment by PeterGamma** [comment]
Garmin watches can now Broadcast Garmin Optical HR to Apps Like Zwift // ANT & Bluetooth:

https://www.youtube.com/watch?v=vuOcAP_7uec

**Comment by fg1** [comment]
Since I do not the devices mentioned in this issue, I cannot extend or test such device by myself.
Feel free to fork if you wish to add support for such device.
