### ISSUE TITLE
Note method for allowing non-root invocation

### ISSUE THREAD

**Issue by kortschak** [fg1/BLEHeartRateLogger#13]
The setcap command can be used to give `hcitool` permission to be used by users other than root.
```
sudo setcap cap_net_raw+eip $(eval readlink -f `which hcitool`)
sudo setcap cap_net_admin+eip $(eval readlink -f `which hciconfig`)
```
Is adequate (`gatttool` does not appear to need capability changes).

**Comment by fg1** [comment]
Thank you! The README was updated to include the commands.
