### ISSUE TITLE
support to run on Linux phone or Linux watch?

### ISSUE THREAD

**Issue by PeterGamma** [fg1/BLEHeartRateLogger#14]
Does this app also work on a Linux phone (e.g. a PinePhone) or a Linux watch (e.g. a LG G Watch Urbane running Linux AsteroidOS?):

https://petergamma.org/read-out-sensor-data-from-the-adafruit-clue-pyloton/

**Comment by fg1** [comment]
Since I do not the devices you mention, I cannot extend or test such feature by myself. Feel free to fork if you wish to add such feature.
