### ISSUE TITLE
Is there an example how to call the BLEHeartRateLogger from Octave? 

### ISSUE THREAD

**Issue by PeterGamma** [fg1/BLEHeartRateLogger#15]
to run the Matlab example «Collect Data from Fitness Monitoring Devices»:

https://ch.mathworks.com/help/matlab/import_export/collect-data-from-fitness-monitoring-devices.html

in Octave with it, which adds foot pod support to the BLEHeartRateLogger, so that the Matlab example can run without Matlab?

**Comment by fg1** [comment]
The data collected by this script is written in a SQLite database. You should then be able to read this database with Octave or Matlab. Feel free to fork if you wish to add a direct interface with Octave.
