### ISSUE TITLE
How can this code be modified to collect speed and cadence from a foot pod?

### ISSUE THREAD

**Issue by PeterGamma** [fg1/BLEHeartRateLogger#16]
So that it can be used as the Matlab example «Collect Data from Fitness Monitoring Devices»:

https://ch.mathworks.com/help/matlab/import_export/collect-data-from-fitness-monitoring-devices.html

a BLE heart rate sensor combined with a BLE foot pod? Then whe would almost be there for a open source Linux sports watch:

https://petergamma.org/page-2/

I am searching since a long time for these components:

https://github.com/PeterGamma/Live-stream-of-ANT-plus-and-BLE-sensor-data

This approach here looks very promising.

**Comment by fg1** [comment]
The code connects to a BLE device using gatttool and reads the heart-rate bluetooth characteristic. You can modify the characteristic in the code to collect other information (such as speed or cadence) if necessary.
