### ISSUE TITLE
Tested Devices

### ISSUE THREAD

**Issue by mcerticky** [fg1/BLEHeartRateLogger#3]
Hi, 
i've tried to run the logger on Fitbit Surge device, but it couldn't handle the HR data coming from the device. There were some issues with the connection also (only connected once before needing another BT restart and was reading the battery data incorrectly). 
Anyway, I'm looking into getting another type of BLE device for reading real-time HR data for my research since Fitbit is not really making things easy when trying to get real-time data.

What devices have you successfuly tested with the script? This might really help me choosing the right one. I'm hoping to get some commercially available fitness wristband (xiaomi mi band/garmin/lamax bfit/etc.), but I'd like to be sure the device would work if it's possible. 

Thanks!

**Comment by fg1** [comment]
Hi! I'm aware of the two following devices: Polar H7 and Zephyr HxM Smart heart rate monitors. I did not get any feedback on other devices for the moment.

If you wish to buy another device, you have to check that it supports live broadcasting of heart-rate value over Bluetooth Low Energy. The goal of this script is to get "live real-time" data, which is usually not supported by the fitness band you listed.

**Comment by fg1** [comment]
The README was updated to list the devices supported. Feel free to extend the list with other devices.
