### ISSUE TITLE
Tomtom HR monitor

### ISSUE THREAD

**Issue by benleov** [fg1/BLEHeartRateLogger#4]
Hi,

Not sure where to put this, but in order to get this to work with a Tom Tom heart rate monitor I needed to modify the code to use "char-desc" instead of "characteristics", as the notification handle 00002902 didn't show up using the latter.

Secondly, I needed to append "-t random" to the gattool connect command, otherwise it would never connect.

I don't know if these changes are related to the version of gattool or hcitool (5.37), but perhaps you find this interesting nonetheless.

Thanks for sharing the project.

**Comment by fg1** [comment]
Hey, thanks for the feedback! It's always welcome to know that my tool is working with other devices.
I'll have a look into the difference between "char-desc" and "characteristics" in gatttool.
